### PR TITLE
Modified

### PR DESCRIPTION
**Pull request by tolsicsse**
A version running with the following changes:
- trains with images without labels since I have only one label that I am interested in, and it seems to work with --use-train-aug
-  added customizable caching to speed up, and adding persistent workers and pre-fetching, which on my laptop speeds up training from 17 sek/iteration to 4.5-5.5 sek/iteration
- Also it loads any of specified image types (previously, it only loaded *.jpg

### CODE REVIEW

**Comment by tolsicsse** [comment]
OK, I am running it on both Ubuntu and Windows without any problem.
I will check if I can understand the problems.

**Comment by tolsicsse** [comment]
Update: I have downloaded the Aquarium Combined.v2-raw-1024.voc from roboflow and I have no problem running the script. Have you tried looking at the missing file: '../../input/Aquarium Combined.v2-raw-1024.voc/train\\IMG_2274_jpeg_jpg.rf.2f319e949748145fb22dcb52bb325a0c.xml' ? It seems to mix linux and windows seperators.

I have a Geforce RTX 3070 with 8GB, and my computer has 32GB RAM.

**Comment by sovit-123** [comment]
Thanks for the update. Yes, the dataset issue may be caused by path separators.
My Windows system is Windows 11 + GTX 1060 laptop GPU. I will test with less number of workers. And yes, maybe we can make the persistent workers optional. Because without it, the code in master branch works.
Further, if you can take a look at the mosaic augmentation merging black pixels, maybe I can merge the PR as soon as you can fix that.

**Comment by tolsicsse** [comment]
I have misunderstood how the augmentation works. I have more or less reverted back to your original code so it works now but the I am not sure how to do the caching. I would like to cache calls to load_image_and_labels but it returns both the original image and the resized image. If I cache the original image the cache becomes too large. However, if I understand correctly, the original image is never used, only resized after load_image_and_labels, is that correct? Then if I remove the returned original image it will only cache the resized image, which in my case is much better.

**Comment by tolsicsse** [comment]
OK, I have now removed permanent workers, prefetch and caching. Only allowed unlabelled images. I also fixed a bug that torchinfo is always run on cuda:0 so added device to summary call. Also added possibility to entirely disable wandb since it was interfering with starting script in background. However these should not affect anything else. To enable mosaic augmentation I needed to remove that it repeats until there is at least one label.

**Comment by tolsicsse** [comment]
Also, I notice that it works quite well without caching and the other additions. The issue I had in the beginning seem not to be a problem on my Ubuntu server.

**Review by sovit-123 — APPROVED** [review]

**Comment by sovit-123** [comment]
@tolsicsse 
PR merged. Thank you for this useful contribution.

**Pull request merged**
