### PR TITLE
Some changes in train.py

### PR DESCRIPTION
**Pull request by falibabaei**
Hi,

I notice that some args are not used in the main function and one of them is used but not defined as an args

### CODE REVIEW

**Comment by sovit-123** [comment]
Hello, the world_size and rank arguments are actually needed for distributed training.
Removing them will cause issues with multi-GPU training.
Regarding `--device` argument, I will update that to use whatever default device is available.

**Comment by falibabaei** [comment]
To use the repository, could you please add setup.py to your project and also change the dashes to underlines in the name of the repository?

**Comment by sovit-123** [comment]
@falibabaei 
Thank you for the suggestion. I will try to do so. I have been thinking to add a setup.py to make it available as a package. But it may take some time.

**Comment by sovit-123** [comment]
@falibabaei 
Are you looking for a proper package where everything would be inside a module? I mean, are you asking that I move all the files to a folder, say, `fasterrcnn` and then create a package?

**Comment by falibabaei** [comment]
I create a setup.py for your project, you may of course change it based on what you want. it is like 
from setuptools import setup, find_packages

with open("README.md", "r") as fh:
    long_description = fh.read()

with open("requirements.txt", "r") as fh:
    requirements = [line.strip() for line in fh]

setup(
    name='fasterrcnn-pytorch-training-pipeline',
    version='0.1.0',
    author='Sovit Ranjan Rath',
    author_email='sovitrath5@gmail.com',
    description='A Simple Pipeline to Train PyTorch FasterRCNN Model',
    long_description=long_description,
    long_description_content_type="text/markdown",
    url='https://github.com/sovit-123/fasterrcnn-pytorch-training-pipeline.git',
    license='MIT',
    classifiers=[
        'Intended Audience :: Information Technology',
        'Intended Audience :: System Administrators',
        'License :: OSI Approved :: MIT License',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
    ],
    packages=find_packages(),
    install_requires=requirements
)

**Comment by falibabaei** [comment]
If I understand your question correctly, no, I do not want to move all the files to a directory. I added your repository as a submodule of my API repository (see my repository https://github.com/falibabaei/submarine_animal_det.git). I use your codes inside my API code. Since the name of your repository is fasterrcnn-pytorch-training-pipeline, I had to fork from your repository and rename it to fasterrcnn_pytorch_training_pipeline to be able to import it into my code.

**Comment by sovit-123** [comment]
Got it.

**Comment by sovit-123** [comment]
Hi. 
Thanks for the PR
Can you remove the `train.py` from this PR? I think I may be able to merge the other files after doing a small check.

**Comment by sovit-123** [comment]
I think deleted the `train.py` file by mistake entirely from the repo.

**Comment by falibabaei** [comment]
:o I have it with some changes but from the pull request we can edit it to the original version

**Comment by falibabaei** [comment]
sent it by email

**Comment by sovit-123** [comment]
I get it. But if I merge this, then the entire `train.py` will also get removed from the main branch. I can add it again by doing another push. Just thinking whether there is a better way.

**Pull request closed without merging**
